CREATE SCHEMA IF NOT EXISTS govor;

CREATE EXTENTION 'uuid';

CREATE TABLE IF NOT EXISTS govor.user (
	ID	UUID	PRIMARY KEY	NOT NULL	DEFAULT	uuid_generate_v4(), 
	NAME	TEXT	NOT NULL	UNIQUE,
	PASSWORD TEXT	NOT NULL,
	EMAIL	TEXT	NOT NULL	UNIQUE,
	CREATED_AT	TIMESTAMPTZ	NOT NULL	DEFAULT null(),
	UPDATED_AP	TIMESTAMPTZ	NOT NULL	DEFAULT null()
);

CREATE TYPE LANGUAGE AS ENUM ('Russian', 'Serbian');
CREATE TABLE IF NOT EXISTS govor.document (
	ID	UUID	PRIMARY KEY	NOT NULL	DEFAULT	uuid_generate_v4(), 
	NAME	TEXT,
	LANG TEXT	LANGUAGE, 
	CREATED_AT	TIMESTAMPTZ	NOT NULL	DEFAULT null(), 
	UPDATED_AP	TIMESTAMPTZ	NOT NULL	DEFAULT null(),
	BODY	JSONB	NOT NULL
	USER_ID UUID NOT NULL REFERENCES govor.user(id)
);


CREATE TABLE IF NOT EXISTS govor.translation (
	ID	UUID	PRIMARY KEY	NOT NULL	DEFAULT	uuid_generate_v4(), 
	FROM_DOCUMENT_ID  UUID	NOT NULL REFERENCES govor.document(id),
	TO_DOCUMENT_ID  UUID	NOT NULL REFERENCES govor.document(id),
	CREATED_AT	TIMESTAMPTZ	NOT NULL	DEFAULT null(), 
	UPDATED_AP	TIMESTAMPTZ	NOT NULL	DEFAULT null()
	DEFAULT	BOOLEAN 	NOT NULL DEFAULT 'f'
);


